### ISSUE TITLE
Library validate string vs filename

### ISSUE THREAD

**Issue by retr0h** [garethr/kubeval#108]
The documentation states kubeval can validate a file as follows:

```results, err := kubeval.Validate(fileContents, fileName)```

However, I was hoping to pass kubeval a string containing json or yaml.  Can this be accomplished?

Thanks -
John

**Comment by garethr** [comment]
You'll need the content as a `[]byte` but other than that what you're trying to do should work. The `fileName` is required purely for output/logging purposes.

**Comment by retr0h** [comment]
Thanks @garethr
