### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by hikhvar** [garethr/kubeval#110]
Hello, 
first of all, thank you for this awesome project. We want to integrate it into our toolchain. However we are uncertain about the status of this project. There are some open issues and pull requests. But no feedback of the maintainer. 

@garethr do you still maintain this project? Can we help you to maintain it?

**Comment by towolf** [comment]
I share the same concerns.

**Comment by php-coder** [comment]
@garethr Gently ping :)

**Comment by InAnimaTe** [comment]
I'd like to tack on to this. Just submitted a PR to incorporate this in our own CD pipeline with `helm template`. Pretty convinced this is the only tool of its kind and would like to know that moving forward it has some support behind it.

**Comment by garethr** [comment]
Hi All. I've not had lots of time recently to maintain `kubeval` unfortunately, but will be picking this back up in earnest now I have a bit more time.

I'm also planning on moving this into a separate organisation, and looking for more folks to add as maintainers. Once I have things in order I'll ping folks from this thread to see if you might be interested getting involved.

**Comment by garethr** [comment]
@InAnimaTe @php-coder @hikhvar @towolf. I've shipped a bunch of updates over the last few weeks and have now moved this over to standalone org. I'm actively looking for maintainers to help onboard too if anyone might be interested. Just let me know and I'll set something up.
