### ISSUE TITLE
Kubeval does not work for kubernetes version 1.11.6 and 1.11.7 

### ISSUE THREAD

**Issue by PeterUherek** [garethr/kubeval#111]
I run this command:
```
helm template . | kubeval -v  1.11.6
 
1 error occurred:
	* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.10.12-standalone/statefulset.json: Could not read schema from HTTP, response status is 404 Not Found
```
Is there way how to generate schema for this kubernetes version?

**Comment by garethr** [comment]
Apologies, I've been far too busy of late and am behind on generating the relevant schemas. You can find them in https://github.com/garethr/kubernetes-json-schema.

I'll generate all the outstanding ones this week and try and do a better job of keeping them up to date now I have a bit more time on my hands.

**Comment by garethr** [comment]
I've pushed lots of new schema versions today, including 11.6 and 11.7. Hopefully this should work now.
