### ISSUE TITLE
garethr/kubeval:0.8.1 missing from dockerhub container registry

### ISSUE THREAD

**Issue by alanjcastonguay** [garethr/kubeval#119]
https://github.com/garethr/kubeval/releases/tag/0.8.1 was published, fixing the issue with full domain API groups in commit acbe5159. But no 0.8.1 container image was published to https://hub.docker.com/r/garethr/kubeval/tags

Did something break in CICD? Or is this manual?

**Comment by garethr** [comment]
I've just pushed this image, it should be available now.

**Comment by alanjcastonguay** [comment]
Thank you, works great.
