### ISSUE TITLE
missing docker image for 0.6.0

### ISSUE THREAD

**Issue by gunjan5** [garethr/kubeval#31]
I don't see version `0.6.0` tag on Dockerhub https://hub.docker.com/r/garethr/kubeval/tags/

Seems like `0.6.0` was cut 5 days ago and last update on Dockerhub was 11 days ago, so I'm guessing the `offline` tag is not for `0.6.0`

**Comment by garethr** [comment]
@gunjan5 thanks for the prompt. I still need to setup something to automate the image builds. The last time I checked Hub didn't support multi-stage builds but I'm sure it will do soon. I've just pushed new images now.
