### ISSUE TITLE
kind: List results in a 404 from default schema location

### ISSUE THREAD

**Issue by anderslauri** [garethr/kubeval#35]
Hi,

First of all great tooling, highly looked after something similar. I have noticed a problem however, we have many different types of OpenShift configurations which are of the quite generic parental kind *List*. Attempting to validate those configuration files with the default schema location results in a 404 - given as no list.json exists within (in example) https://github.com/garethr/openshift-json-schema/tree/master/v3.6.0-standalone

**Comment by garethr** [comment]
Thanks for reporting. I'll need to look into the OpenApi description for OpenShift and see if it contains this object, or whether it's regarded as an implementation detail (and needs some special handling)

**Comment by garethr** [comment]
Ah ha. This also comes up in #33 so I'll close this issue in favour of that one.
