### ISSUE TITLE
Witout TTY docker on CI

### ISSUE THREAD

**Issue by albertoig** [garethr/kubeval#36]
I am triying to use kubeval on docker without TTY to validate YML on CI but give me this error "The document stdin appears to be empty". How i can use it without TTY?

**Comment by garethr** [comment]
Hi @albertoig could you post an example of the command you're running? I'll try and recreate.

**Comment by albertoig** [comment]
Hi!

I am using Gitlab CI with some pipelines to deploy a project. I think is interesting to validate my YML kubernetes files with Kubeval. I execute on a pipeline this thing like this:

`
yaml-validator:
  stage: doctor
  image: garethr/kubeval
  tags:
    - linux
    - docker
  script:
    - kubeval -v 1.8.1 ./deploy/*
`

If a execute on terminal it work because the docker commmand use TTY, but gitlab CI does not. Why the kubeval have to be TTY?

![captura de pantalla 2017-11-23 a las 17 17 59](https://user-images.githubusercontent.com/6804337/33181949-4e3f55e6-d072-11e7-9ee6-09b3c965d2f2.png)

**Comment by albertoig** [comment]
I am not expert on Go, but i know that the issue is related to [this line](https://github.com/garethr/kubeval/blob/5af429f8feefcfa4b514f5ff87269e3e3319db73/cmd/root.go#L30)

Do you think is posible to change it to fmt.Printf?

Thanks

**Comment by johscheuer** [comment]
@albertoig I solved this issue by running `kubeval` with [script](http://man7.org/linux/man-pages/man1/script.1.html) e.g.`script -q -e -c "kubeval -v 1.8.1 ./deploy/*"`

**Comment by xanonid** [comment]
@albertoig @johscheuer  You can also redirect stdin from `/dev/null`: `kubeval *.yaml < /dev/null`

**Comment by Tombar** [comment]
FTR the same thing happens when using kubeval in the context of an ansible template validation

```yaml
    - name: setup-k8s | template image pull secret
      template:
        src: k8s/image-pull-secret.yml.j2
        dest: "{{ deploy_dir }}/010-image-pull-secret.yml"
        validate: '/usr/bin/kubeval %s'
      tags: k8s-tasks
```

```bash
TASK [setup-k8s | template image pull secret] ****************************************************************************************************************
Tuesday 06 March 2018  03:13:00 +0000 (0:00:01.031)       0:00:10.130 *********
fatal: [localhost]: FAILED! => {"changed": false, "checksum": "28a4d034ca2f8202789bb7e0ac11439c06fa0ff1", "exit_status": 1, "msg": "failed to validate", "stderr": "", "stderr_lines": [], "stdout": "***PRINTED BY CALLBACK***", "stdout_lines": "***PRINTED BY CALLBACK***"}

stdout: The document stdin appears to be empty
```

the `script -q -e -c ` workaround seems to work only for some cases where the `< /dev/null` doesn't work in any scenario

**Comment by Neirda24** [comment]
Having the same trouble here.... :/ can't find a way around so far...

**Comment by Neirda24** [comment]
@garethr : Hi, we greatly appreciate your work on this. It helps us a lot when debugging helm on local with no access to a kubernetes cluster. We'd like to use it in our CI as well (gitlab-ci) (see the above post). Do you have any news on this bug ?

**Comment by keegancsmith** [comment]
This is an issue without how kubeval decides to use STDIN vs reading files from arguments. You can very easily reproduce with the docker image provided

```
docker run --rm=true --entrypoint=/bin/sh -v `pwd`/fixtures:/fixtures garethr/kubeval:0.7.1 -c 'find /fixtures | xargs /kubeval'
```

I don't know why kubeval checks stdin's mode to decide to use stdin. Every other tool I know of just uses stdin if no args are provided or have `-` mean stdin.

https://github.com/garethr/kubeval/blob/master/cmd/root.go#L42-L43
