### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by kauedb** [garethr/kubeval#37]
1 error occurred:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/deployment.json: Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/deployment.json: x509: certificate signed by unknown authority

**Comment by garethr** [comment]
Mmm, sorry for the delay in getting to look at this issue. I've not been able to recreate it, sounds like it could have been a transient issue with GitHub? If this is still happening if you could provide more details, and maybe just raw output from `curl` with the headers?

**Comment by garethr** [comment]
I'll close this issue for now, but if it's still occurring please do reopen and provide more details and I'll take a closer look.
