### ISSUE TITLE
Kubeval fails validation when yaml contains multi-line scalar

### ISSUE THREAD

**Issue by hobbsh** [garethr/kubeval#38]
Is it expected behavior for kubeval to fail validation on a configmap that contains a multi-line scalar, i.e. (from the docs): 

```
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30
```

If that data is crunched into JSON, it validates fine. From a readability/maintainability standpoint it's much easier to be able to use the multi-line scalar, especially with configmaps like nginx. Is this something we will need to use a custom schema for?

The actual error is:
```
* Failed to decode YAML from my-configmap.yml
Exited with code 123
```

**Comment by garethr** [comment]
Thanks for reporting. I'll add a test case for this and try and find a fix. This could be an issue with the YAML parser I'm using?

**Comment by hobbsh** [comment]
So, this appears to be an issue with the prebuilt linux binary for 0.7.0. I just built it myself locally because I planned on helping solve this problem and went to test a configmap with a multiline scalar and it passes.

**Comment by garethr** [comment]
Mmmm, interesting. I'll have a look at why that might be, but glad it's working now. If you want to provide a full config example I can include it in the test suite so I can catch future issues like this. Just reply here, although I'll close the issue for now. Thanks.
