### ISSUE TITLE
docker image fails when -it not specified

### ISSUE THREAD

**Issue by elaygl** [garethr/kubeval#40]
I'm trying to use kubeval docker image with Teamcity.
When `-it` is not specified I'm getting the following error: 
`The document stdin appears to be empty`

The command I used: 
`docker run --rm -v $(pwd)/namespaces:/namespaces garethr/kubeval:offline namespaces/*`

**Comment by garethr** [comment]
I think this is the same issue described in #36, which has a few workarounds. I'm looking at making this simpler/documenting the behaviour. I'll close this particular issue but thanks for reporting.
