### ISSUE TITLE
Question: Does kubeval check the existence of secrets/configmap and proper keys?

### ISSUE THREAD

**Issue by yayajacky** [garethr/kubeval#41]
Hi, this looks like a very interesting project.
I am wondering if this tool take into consideration of the current running context.

Thanks and have a good day!

**Comment by garethr** [comment]
Hi @yayajacky. Sorry for the delay in responding. At the moment, no, `kubeval` is interpreting only the files you pass in, not the state of the cluster. If you have specific examples that you think would make sense for `kubeval` please do let me know.
