### ISSUE TITLE
DaemonSet schema not found when using --kubernetes-version=1.8.5 and --strict

### ISSUE THREAD

**Issue by mattnworb** [garethr/kubeval#46]
I may be misunderstanding the differences between the various flavors of schemas in https://github.com/garethr/kubernetes-json-schema but I was surprised that when running `kubeval` with `--kubernetes-version=1.8.5 --strict` that the schema for DaemonSet could not be found:

```
1 error occurred:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.8.5-standalone-strict/daemonset.json: Could not read schema from HTTP, response status is 404 Not Found
```

**Comment by mattnworb** [comment]
`daemonset.json` does not exist in the kubernetes-json-schema repo for any 1.8.x version with `--strict`

**Comment by garethr** [comment]
Mmmm, interesting. Thanks for reporting. I'll try and track down the problem - likely in the schema generation.

**Comment by garethr** [comment]
I've regenerated all the of the schemas after fixing a few issues. This should now work as expected. For instance the schema referenced is available at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.8.5-standalone-strict/daemonset.json

**Comment by mattnworb** [comment]
thanks!
