### ISSUE TITLE
how to handle custom resources

### ISSUE THREAD

**Issue by jurgenweber** [garethr/kubeval#48]
I recenetly just implemented https://github.com/jetstack/cert-manager which comes with a few custom resources.....

Now my CI fails using kubeval with `https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.8.6-standalone/clusterissuer.json` obviously, because why would you have a definition for that?

What is the best way to handle this. my CI/CD checks for every yaml and then tries to validate it hence why I am getting this.. I could exclude it there with some trickery but I thought there might be a better way and to ask here?

Thanks

**Comment by garethr** [comment]
Thanks for opening the issue. I have a few ideas for CRDs but haven;t had the time to try any of them out as yet. I'll close this issue as it's covered in #47. At the least this should be documented and have better error handling.
