### ISSUE TITLE
Could not open file fixtures/*

### ISSUE THREAD

**Issue by TheKangaroo** [garethr/kubeval#49]
Issuing the command 
```
docker run -it -v `pwd`/Files:/fixtures garethr/kubeval fixtures/*
```
throws  a 'Could not open file fixtures/*' error on my MacBook.
Choosing a specific file works like a charm.
So I think the problem is with the asterisk.
Any hints?

**Comment by TheKangaroo** [comment]
Figured this one out, the mounting won't work with different names. 
(-v `pwd`/Files:/fixtures)
Since my local folder is called Files I changed the command to
```
docker run -it -v `pwd`/Files:/Files garethr/kubeval Files/*
```
But I'm not quite sure what's the problem here...

**Comment by garethr** [comment]
Mmmm, interesting. Glad you found a workaround for now. I'll try and recreate this when I get a moment and come back with any questions.

**Comment by garethr** [comment]
So I think the problem here is that the wildcard expansion happens locally, not inside the container. So this works when you have the same folder name, or rather it does with the shell you're using. Looking around this is more a limitation/how docker works. I'll close for now as I don't _think_ this is something I can work around on my end.

**Comment by stephan-rayner** [comment]
This is still a thing that happens I ran into this about an hour ago. The folder naming trick is not bad but I think I may have something a little better. By using the `-d` flag you can specify the folder in the container, in this case I called it `fixtures/`.

```
docker run -it -v $PWD/Files/fixtures garethr/kubeval -d fixtures
```

I hope this helps someone :slightly_smiling_face:

**Comment by rufreakde** [comment]
if it is okay for you to go through the folders recursivly what worked for me was to use the following command instead:
```sh
kubeval  --directories ./templates/
```
