### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by fiunchinho** [garethr/kubeval#5]
Would it make sense to make travis publish a Docker image for every new release? That way it would be even easier to install and use `kubeval`.

**Comment by garethr** [comment]
@fiunchinho thanks for the suggestions. I have a local version of this I'll get up in a PR for testing soon. Do you have opinions about the interface for this?

Do you think it works to mount the files you want to test? ie.

```
docker run -v `pwd`:/ garethr/kubeval some-kubernetes-file.yaml
```

Or did you have something different/nicer in mind?

**Comment by fiunchinho** [comment]
I think mounting is fine.

**Comment by garethr** [comment]
I've put up a PR in #6, and published the resulting image to Hub. @fiunchinho if you have a moment to try that out and see if it works for you I'll merge.

I'll add more metadata and the link once we're happy with the basic image.

**Comment by garethr** [comment]
I've merged this and shipped an image to Hub https://hub.docker.com/r/garethr/kubeval/
