### ISSUE TITLE
Release checksums with builds?

### ISSUE THREAD

**Issue by hodgesmr** [garethr/kubeval#50]
I noticed you have targets in the Makefile to calculate checksums. Would it be possible to release those as well?

**Comment by garethr** [comment]
Good idea. I generate those for the chocolatey and homebrew packages, I can definitely include them in the release notes section as well. I'll keep this open until the next release as a reminder. Thanks for the suggestion.

**Comment by garethr** [comment]
I've added the checksums for 0.7.1 to the release notes. https://github.com/garethr/kubeval/releases/tag/0.7.1
