### ISSUE TITLE
Kubeval fails when resource contains '----'

### ISSUE THREAD

**Issue by ant1441** [garethr/kubeval#52]
I have a configmap which contains a certificate file:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeval-test-config
data:
  my.crt: |-
    -----BEGIN CERTIFICATE-----
    REDACTED
    -----END CERTIFICATE-----
```

Running `kubeval` against this file fails with the following error:

```
$ kubeval a.configmap.yaml
1 error occurred:

* Missing a kind key
```

I believe this is due to the multi-document YAML support (#9) erroneously splitting the document with the line ending `----`.

**Comment by garethr** [comment]
This should be resolved in master now via #54. I'll be tidying a few things up and shipping a new release soon all being well.
