### ISSUE TITLE
Published SHA256 are wrong due to all-caps

### ISSUE THREAD

**Issue by hodgesmr** [garethr/kubeval#59]
The sha256 checksums published with the releases are in all-caps. For example, [release 0.7.1](https://github.com/garethr/kubeval/releases/tag/0.7.1) shows the binary `kubeval-linux-amd64.tar.gz` with a sha256 of `8259D462BD19E5FC2DB2EA304E51ED4DB928BE4343F6C9530F909DBA66E15713` but when attempting to check the tarball:

```sh
openssl sha -sha256 kubeval-linux-amd64.tar.gz | awk '{print $2}'
8259d462bd19e5fc2db2ea304e51ed4db928be4343f6c9530f909dba66e15713
```

which uses lowercase a-f.

**Comment by garethr** [comment]
Ah, I downcase in the package specs. I'll get these fixed. Thanks for the heads up.

**Comment by garethr** [comment]
Thanks, I've updated these to use the correct lowercase hashes, and updated the Makefile in https://github.com/garethr/kubeval/commit/ca381ba65e3da4fb77ccc1778b9e0d48b1730fe5
