### ISSUE TITLE
Unable to Run.

### ISSUE THREAD

**Issue by saviour123** [garethr/kubeval#60]
for some strange reason, am not able to run it.
![selection_018](https://user-images.githubusercontent.com/6932272/36829850-ddba9a9e-1d18-11e8-9027-5e901da97446.png)

**Comment by bakins** [comment]
How did you get the binary? Looks like you may have got the wrong one or perhaps got an error when downloading, but still have the file?

**Comment by saviour123** [comment]
I have to clean everything and restart.
