### ISSUE TITLE
Error finding loadbalancer.json

### ISSUE THREAD

**Issue by wooderz** [garethr/kubeval#81]
When running `kubeval myyaml.yaml` I receive the following error:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/loadbalancer.json: Could not read schema from HTTP, response status is 404 Not Found

**Comment by garethr** [comment]
Kubernetes doesn't have a native LoadBalancer object I don't believe, just a type of Service. Maybe this is a CRD or some other extension? Do you have a sample of the configuration which triggers this issue?

**Comment by wooderz** [comment]
Yeah was a misunderstanding, thought I'd closed this! Sorry
