### ISSUE TITLE
error finding template.json

### ISSUE THREAD

**Issue by spolti** [garethr/kubeval#82]
latest released version fails with this message: 

1 error occurred:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/template.json: Could not read schema from HTTP, response status is 404 Not Found

**Comment by garethr** [comment]
Template isn't actually a Kubernetes type, it's specific to OpenShift. You can use the `--openshift` flag to toggle between the two sets of schemas which I think should work.
