### ISSUE TITLE
x509 issue 

### ISSUE THREAD

**Issue by BenCoughlan15** [garethr/kubeval#83]
Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/serviceaccount.json: Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/serviceaccount.json: x509: certificate signed by unknown authority
* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/clusterrolebinding.json: Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/clusterrolebinding.json: x509: certificate signed by unknown authority
* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/service.json: Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/service.json: x509: certificate signed by unknown authority
* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/ingress.json: Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/ingress.json: x509: certificate signed by unknown authority
* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/configmap.json: Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.7.1-standalone/configmap.json: x509: certificate signed by unknown authority

**Comment by garethr** [comment]
I've not been able to recreate this, it appears to be transient based on reports and somewhere between the go http client and GitHub.
