### ISSUE TITLE
network issue when validating, can provide local version schema per version

### ISSUE THREAD

**Issue by jdxyw** [garethr/kubeval#84]
Sometimes, it would fail because of network issue when validating, can provide local version schema per version

such as 
Get https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone-strict/deployment.json: net/http: TLS handshake timeout

**Comment by khiety** [comment]
+1

**Comment by garethr** [comment]
You can download the schemas or generate your own, and point kubeval at those using `--schema-location` or the accompanying ENV. You can see this in action with the offline images: https://github.com/garethr/kubeval/blob/master/Dockerfile.offline
